apiVersion: v1
kind: Service
metadata:
  name: loginhub-notification
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: loginhub-notification
  ports:
    - name: notification
      port: 8002
      targetPort: 8000
      protocol: TCP
