apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginhub-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginhub-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: loginhub-auth
    spec:
      containers:
        - name: loginhub-auth
          image: asia-east1-docker.pkg.dev/loginhub-dev/main-repo/loginhub-3-auth:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: auth
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/healthy
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 1
          env:
            - name: PORT
              value: "8000"
            - name: API_VERSION
              value: "v1"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: jwt-token
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: client-url
            - name: API_GATEWAY_URL
              value: "http://loginhub-gateway.production.svc.cluster.local:8000"
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: rabbitmq-endpoint
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: postgres-auth-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: postgres-auth-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: postgres-auth-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: postgres-auth-db
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: postgres-auth-port
            - name: CLUSTER_TYPE
              value: "GCP"
