apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginhub-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginhub-queue
  template:
    metadata:
      labels:
        app: loginhub-queue
    spec:
      containers:
        - name: loginhub-queue
          image: rabbitmq:3.13.4-management-alpine
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              memory: 150Mi
              cpu: 100m
          ports:
            - name: queue
              containerPort: 5672
              protocol: TCP
            - name: mgmt
              containerPort: 15672
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - status
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - status
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 60
            failureThreshold: 3
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: rabbitmq-password
          volumeMounts:
            - name: rabbittmq-local-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbittmq-local-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
