apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-gcp-storage
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-standard
  replication-type: none
reclaimPolicy: Delete
