apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginhub-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loginhub-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: loginhub-auth
    spec:
      containers:
        - name: loginhub-auth
          image: rulerchen/loginhub-3-auth:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: auth
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: API_VERSION
              value: "v1"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: jwt-token
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: loginhub-backend-secret
                  key: client-url
            - name: API_GATEWAY_URL
              value: "http://loginhub-gateway.production.svc.cluster.local:8000"
            - name: RABBITMQ_ENDPOINT
              value: amqp://loginhub:loginhub@loginhub-queue.production.svc.cluster.local:5672
            - name: DATABASE_HOST
              value: loginhub-postgres-auth.production.svc.cluster.local
            - name: DATABASE_USER
              value: loginhub
            - name: DATABASE_PASSWORD
              value: loginhub
            - name: DATABASE_NAME
              value: loginhub-auth
            - name: DATABASE_PORT
              value: "5432"
            - name: CLUSTER_TYPE
              value: "local"
