apiVersion: v1
kind: Service
metadata:
  name: loginhub-auth
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: loginhub-auth
  ports:
    - name: auth
      port: 8003
      targetPort: 8000
      protocol: TCP
